language: c
compiler:
  - clang
  - gcc
script: ./configure && make clean && make sql
notifications:
  email:
    recipients:
		- greenboxal@gmail.com
		- kayu09@hotmail.com
		- matheus.freitas97@gmail.com
		- atendimento@virtuati.com.br